// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: AssemblyTitle("Mason.Foundation")>]
[<assembly: AssemblyProduct("Mason.Foundation")>]
[<assembly: AssemblyDescription("")>]
[<assembly: AssemblyCompany("Virtual Dimensions")>]
[<assembly: AssemblyCopyright("Copyright © Virtual Dimensions 2017-2019")>]
[<assembly: AssemblyTrademark("")>]
[<assembly: AssemblyConfiguration("Debug")>]
[<assembly: AssemblyCulture("")>]
[<assembly: System.Runtime.InteropServices.GuidAttribute("f46be8de-7918-48af-b19f-4d33a4fd6d79")>]
[<assembly: AssemblyVersion("")>]
[<assembly: AssemblyFileVersion("")>]
[<assembly: AssemblyInformationalVersion("")>]
do()
